//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MillionBeauty.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MillionBeauty.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap AboutMB {
            get {
                object obj = ResourceManager.GetObject("AboutMB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap AddCustomer {
            get {
                object obj = ResourceManager.GetObject("AddCustomer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Customer.
        /// </summary>
        internal static string AddNewCustomer {
            get {
                return ResourceManager.GetString("AddNewCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Product.
        /// </summary>
        internal static string AddNewProduct {
            get {
                return ResourceManager.GetString("AddNewProduct", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap AddOrder {
            get {
                object obj = ResourceManager.GetObject("AddOrder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap AddProduct {
            get {
                object obj = ResourceManager.GetObject("AddProduct", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.00}.
        /// </summary>
        internal static string CurrencyFormat {
            get {
                return ResourceManager.GetString("CurrencyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d+([-+.]\d+)?$.
        /// </summary>
        internal static string CurrencyPattern {
            get {
                return ResourceManager.GetString("CurrencyPattern", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Customers {
            get {
                object obj = ResourceManager.GetObject("Customers", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers List.
        /// </summary>
        internal static string CustomersList {
            get {
                return ResourceManager.GetString("CustomersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Version {0}.
        /// </summary>
        internal static string DatabaseVersion {
            get {
                return ResourceManager.GetString("DatabaseVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data source=&quot;{0}&quot;.
        /// </summary>
        internal static string DataSource {
            get {
                return ResourceManager.GetString("DataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete order {0}.
        /// </summary>
        internal static string DeleteOrder {
            get {
                return ResourceManager.GetString("DeleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete product {0}.
        /// </summary>
        internal static string DeleteProduct {
            get {
                return ResourceManager.GetString("DeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Order.
        /// </summary>
        internal static string EditOrder {
            get {
                return ResourceManager.GetString("EditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has detected that your user settings file has become corrupted. This may be due to a crash or improper exiting of the program. {0} must reset your user settings in order to continue.\n\nClick Yes to reset your user settings and continue.\n\nClick No if you wish to attempt manual repair or to rescue information before proceeding..
        /// </summary>
        internal static string ErrorCorrupSettingMessage {
            get {
                return ResourceManager.GetString("ErrorCorrupSettingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrupt user settings.
        /// </summary>
        internal static string ErrorCorrupSettingTitle {
            get {
                return ResourceManager.GetString("ErrorCorrupSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name can not be empty..
        /// </summary>
        internal static string ErrorCustomerName {
            get {
                return ResourceManager.GetString("ErrorCustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount has to be percentage format and can not be empty..
        /// </summary>
        internal static string ErrorDiscountFormat {
            get {
                return ResourceManager.GetString("ErrorDiscountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name, In Stock and Price can not be empty..
        /// </summary>
        internal static string ErrorNameEmpty {
            get {
                return ResourceManager.GetString("ErrorNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a product before adding to order form..
        /// </summary>
        internal static string ErrorPickProduct {
            get {
                return ResourceManager.GetString("ErrorPickProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price has to be price format and can not be empty..
        /// </summary>
        internal static string ErrorPriceFormat {
            get {
                return ResourceManager.GetString("ErrorPriceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name can not be empty..
        /// </summary>
        internal static string ErrorProductName {
            get {
                return ResourceManager.GetString("ErrorProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity can not be more then in stock quantity..
        /// </summary>
        internal static string ErrorQuantity {
            get {
                return ResourceManager.GetString("ErrorQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity can not be zero..
        /// </summary>
        internal static string ErrorQuantityZero {
            get {
                return ResourceManager.GetString("ErrorQuantityZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount has to be RM format and can not be empty..
        /// </summary>
        internal static string ErrorRebate {
            get {
                return ResourceManager.GetString("ErrorRebate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-enter password not the same. Please try it again..
        /// </summary>
        internal static string ErrorReenterPassword {
            get {
                return ResourceManager.GetString("ErrorReenterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock quantity has to be a number and can not be empty..
        /// </summary>
        internal static string ErrorStockQuantity {
            get {
                return ResourceManager.GetString("ErrorStockQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password. Please try it again..
        /// </summary>
        internal static string ErrorWrongPassword {
            get {
                return ResourceManager.GetString("ErrorWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Million Beauty Data files (*.db)|*.db|All files (*.*)|*.*.
        /// </summary>
        internal static string FileFilter {
            get {
                return ResourceManager.GetString("FileFilter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon mb {
            get {
                object obj = ResourceManager.GetObject("mb", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Order.
        /// </summary>
        internal static string NewOrder {
            get {
                return ResourceManager.GetString("NewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\d+$.
        /// </summary>
        internal static string NumberPattern {
            get {
                return ResourceManager.GetString("NumberPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Million Beauty Data File.
        /// </summary>
        internal static string OpenFileTitle {
            get {
                return ResourceManager.GetString("OpenFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Orders {
            get {
                object obj = ResourceManager.GetObject("Orders", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders List.
        /// </summary>
        internal static string OrdersList {
            get {
                return ResourceManager.GetString("OrdersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password changed..
        /// </summary>
        internal static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick.
        /// </summary>
        internal static string Pick {
            get {
                return ResourceManager.GetString("Pick", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Products {
            get {
                object obj = ResourceManager.GetObject("Products", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products List.
        /// </summary>
        internal static string ProductsList {
            get {
                return ResourceManager.GetString("ProductsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restart the application with this new database.
        /// </summary>
        internal static string RestartApplication {
            get {
                return ResourceManager.GetString("RestartApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will restart and load this new database.
        /// </summary>
        internal static string RestartLoadDatabase {
            get {
                return ResourceManager.GetString("RestartLoadDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Million Beauty Data File.
        /// </summary>
        internal static string SaveFileTitle {
            get {
                return ResourceManager.GetString("SaveFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Customer.
        /// </summary>
        internal static string SelectCustomer {
            get {
                return ResourceManager.GetString("SelectCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Product.
        /// </summary>
        internal static string SelectProduct {
            get {
                return ResourceManager.GetString("SelectProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of {0} is already running. Please close other instances of {0} before launching {0}..
        /// </summary>
        internal static string SingleInstanceMessage {
            get {
                return ResourceManager.GetString("SingleInstanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Million Beauty.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Tools {
            get {
                object obj = ResourceManager.GetObject("Tools", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Customer Info.
        /// </summary>
        internal static string UpdateCustomerInfo {
            get {
                return ResourceManager.GetString("UpdateCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Product Info.
        /// </summary>
        internal static string UpdateProductInfo {
            get {
                return ResourceManager.GetString("UpdateProductInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
